database:
  username: postgres
  password: boofhichkas
  port: 5432
  ssl_mode: disable
  host: 127.0.0.1
  name: hotel_reservation
  engine: postgres
application:
  port: 8080
  cluster_name: cluster1
  ignore_migration: false
  debug_mode: true
  metric_end_point_port: 8081
  allowed_origins: '*'
minio:
  endpoint: 127.0.0.1:9000
  access_key_id: minioadmin
  secret_access_key: minioadmin
  use_ssl: false
messagebroker:
  url: amqp://guest:guest@localhost:5672/
  management: http://localhost:15672/

smtp:
  host: smt.p.test
  username: test
  password: test
  port: 857
authentication:
  jwt_key: test123$%!@@#%%&YU&*
  token_alive_time: 520

redis:
  addr: localhost:6379
  password:
  cache_db: 0