database:
  username: postgres
  password: 1234
  port: 5432
  ssl_mode: disable
  host: 127.0.0.1
  name: hotel_reservation
  engine: postgres
application:
  port: 80
  cluster_name: cluster1
  ignore_migration: false
  sql_debug: true
minio:
  endpoint: 127.0.0.1:9000
  access_key_id: minioadmin
  secret_access_key: minioadmin
  use_ssl: false
messabebroker:
  url: amqp://guest:guest@localhost:5672/
  management: http://localhost:15672/