database:
  username: postgres
  password: 1234
  port: 5432
  ssl_mode: disable
  host: 127.0.0.1
  name: hotel_reservation
  engine: postgres
application:
  port: 8080
  cluster_name: cluster1
  ignore_migration: false
  sql_debug: true
minio:
  endpoint: http://127.0.0.1:9000
  access_key_iD: miniosecret
  secret_access_key: miniosecret
  use_ssl: false